name: Daily GPT Digest

on:
  schedule:
    - cron: '30 5 * * *'  # 한국 시간 오전 8시 = UTC 기준 전날 23시
  workflow_dispatch:       # 수동 실행도 가능하게

jobs:
  ask-chatgpt:
    runs-on: ubuntu-latest

    steps:
      - name: Ask ChatGPT and send to Slack
        run: |
          curl https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "model": "gpt-3.5-turbo",
              "messages": [
                {"role": "user", "content": "오늘의 AI 트렌드 3가지를 요약해줘. 100자 이내로 간결하게."}
              ]
            }' | jq -r '.choices[0].message.content' > result.txt

          curl -X POST -H 'Content-type: application/json' \
            --data "{"text":"$(cat result.txt)"}" \
            ${{ secrets.SLACK_WEBHOOK_URL }}
